name: ai_auction
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_transform: ^1.2.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  cupertino_icons: ^1.0.2
  kakaomap_webview: ^0.3.0
  get: ^4.6.1
  http: 0.13.4
  flutter_naver_login: ^1.2.4
  flutter_native_splash: ^1.3.2
  fl_chart: ^0.41.0
  fluttertoast: ^8.0.8
  flutter_secure_storage: ^5.0.2
  slimy_card: ^1.0.4
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/json/
flutter_native_splash:
  image: images/app_logo.png
  color: "#FFFFFF"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"